create table university(
                           id int generated by default as identity primary key,
                           name varchar(100) not null,
                           address varchar(100) not null,
                           foundation_year int check ( foundation_year > 0 ),
                           website varchar(100)
);


create table faculty(
                        id int generated by default as identity primary key,
                        name varchar(100) not null ,
                        code varchar(20) not null ,
                        gpa float4 check ( gpa > 0 ),
                        description varchar(100),
                        university_id int references university (id) on delete set null
);


insert into university (name, address, foundation_year, website)
values ('BMSTU', 'Moscow, 2nd Baumanskaya str., 5', 1830, 'https://bmstu.ru/');

insert into university (name, address, foundation_year, website)
values ('MEPHI', 'Kashirskoe sh., 31, Moscow', 1942, 'https://mephi.ru/');

insert into university (name, address, foundation_year, website)
values ('MIPT', 'Institutsky Lane, 9, Dolgoprudny', 1946, 'https://mipt.ru/');

insert into university (name, address, foundation_year, website)
values ('MIET', 'Shokina Square, 1, Zelenograd, Moscow', 1965, 'https://miet.ru/');


insert into faculty (name, code, gpa, description, university_id)
values ('IU', '11.03.03', 252, 'Informatics and management system', 1);

insert into faculty (name, code, gpa, description, university_id)
values ('RT', '11.03.04', 207, 'Radio engineering', 1);

insert into faculty (name, code, gpa, description, university_id)
values ('LaPlas', '12.03.05', 281, 'Lasers and Plasma', 2);
